apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "devops-sample-app.fullname" . }}
  labels:
    app: {{ include "devops-sample-app.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "devops-sample-app.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "devops-sample-app.name" . }}
    spec:
      containers:
        - name: {{ include "devops-sample-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.readinessProbe.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.livenessProbe.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
