apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: devops-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/eknathdj/devops-gitops-flux
  ref:
    branch: main
