replicaCount: 2

image:
  repository: docker.io/nginx
  tag: "3596dd2be40daa158f3ecce60185dd9db2dd8d60"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

readinessProbe:
  path: /
  port: 80

livenessProbe:
  path: /
  port: 80
