replicaCount: 2

image:
  repository: docker.io/nginx
  tag: "28fe2ca76e95fd3b0d9c2e7c649059ad7dc4ca66"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

readinessProbe:
  path: /
  port: 80

livenessProbe:
  path: /
  port: 80
