replicaCount: 2

image:
  repository: docker.io/nginx
  tag: "ff95c03c0e71c4421ac531f27d1586f626c3d76f"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

readinessProbe:
  path: /
  port: 80

livenessProbe:
  path: /
  port: 80
