replicaCount: 2

image:
  repository: docker.io/nginx
  tag: "bb2c4faa97d15d7e720ed76e19a776bdc78b87f7"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

readinessProbe:
  path: /
  port: 80

livenessProbe:
  path: /
  port: 80
