replicaCount: 2

image:
  repository: docker.io/nginx
  tag: "latest" # {"$imagepolicy": "flux-system:nginx-image-policy"}
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

readinessProbe:
  path: /
  port: 80

livenessProbe:
  path: /
  port: 80
