replicaCount: 2

image:
  repository: docker.io/nginx
  tag: "733e2105d18f0646a1dc17733f9a7cb1b388a903"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

readinessProbe:
  path: /
  port: 80

livenessProbe:
  path: /
  port: 80
