replicaCount: 2

image:
  repository: ghcr.io/eknathdj/devops-sample-app
  tag: "latest" # {"$imagepolicy": "flux-system:devops-image-policy:name"}
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

readinessProbe:
  path: /
  port: 8080

livenessProbe:
  path: /
  port: 8080
