replicaCount: 2

image:
  repository: docker.io/nginx
  tag: "7dfbd47754de9743b1198def8b5c2702bd4a230a"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

readinessProbe:
  path: /
  port: 80

livenessProbe:
  path: /
  port: 80
