apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: nginx-image-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: nginx-image-repo
  policy:
    alphabetical:
      order: asc
  filterTags:
    pattern: '^[0-9]+\.[0-9]+(\.[0-9]+)?$'
    extract: '$0'
