apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-sample-app
  namespace: rocket-lab
  labels:
    app: devops-sample-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-sample-app
  template:
    metadata:
      labels:
        app: devops-sample-app
    spec:
      containers:
        - name: devops-sample-app
          image: docker.io/eknathdj/nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
