apiVersion: v1
kind: Service
metadata:
  name: devops-sample-svc
  namespace: rocket-lab
spec:
  type: ClusterIP
  selector:
    app: devops-sample-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
