apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ghcr.io/eknathdj/devops-sample-app
    newTag: "latest" # {"$imagepolicy": "flux-system:devops-image-policy:name"}
